# See https://docs.travis-ci.com/user/languages/r/
dist: trusty
language: r
cache:
    packages: yes

before_install:
    - mkdir -p ~/.R
    - echo "CXX14FLAGS=-O3 -mtune=native -march=native -Wno-unused-variable -Wno-unused-function  -Wno-macro-redefined" >> ~/.R/Makevars
    - echo "CXX14=g++ -std=c++1y" >> ~/.R/Makevars

apt_packages:
    - libxml2-dev
    - libv8-dev

r_github_packages:
    - achetverikov/APAstats/apastats

# repos:
# CRAN: https://mran.microsoft.com/snapshot/2018-07-01

script:
    - Rscript -e 'bookdown::render_book("index.Rmd")'

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
    keep-history: true
    local-dir: docs
    verbose: true
