# See https://docs.travis-ci.com/user/languages/r/
dist: trusty
language: r
cache:
    packages: yes

before_install:
    - sudo add-apt-repository -y "ppa:marutter/rrutter"
    - sudo add-apt-repository -y "ppa:marutter/c2d4u"
    - sudo apt-get update -q
    - sudo apt-get install r-cran-rstan -y
    - Rscript -e 'install.packages("devtools");
      devtools::install_github("stan-dev/rstanarm", build_vignettes = FALSE);'

apt_packages:
    - libxml2-dev
    - libv8-dev

r_github_packages:
    - achetverikov/APAstats/apastats

# repos:
# CRAN: https://mran.microsoft.com/snapshot/2018-07-01

script:
    - Rscript -e 'bookdown::render_book("index.Rmd")'

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
    keep-history: true
    local-dir: docs
    verbose: true
