# See https://docs.travis-ci.com/user/languages/r/
dist: trusty
language: r
r: 
    - 3.4

cache:
    packages: yes

before_install:
    - mkdir -p ~/.R/
    - echo "CXX14 = g++-7 -fPIC -flto=2" >> ~/.R/Makevars
    - echo "CXX14FLAGS = -mtune=native -march=native -Wno-unused-variable -Wno-unused-function -Wno-unused-local-typedefs -Wno-ignored-attributes -Wno-deprecated-declarations -Wno-attributes -O3" >> ~/.R/Makevars

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

r_binary_packages:
    arm,
    bayesplot,
    brms,
    broom,
    car,
    coin,
    DAAG,
    data.table,
    emmeans,
    ez,
    GGally,
    gridExtra,
    knitr,
    lavaan,
    lme4,
    mediation
    mice,
    MuMIn,
    pander,
    psych,
    pwr,
    readxl,
    reshape2,
    rstan,
    rstanarm,
    tidyverse,

apt_packages:
    - libxml2-dev
    - libv8-dev

r_github_packages:
    - achetverikov/APAstats/apastats

# repos:
# CRAN: https://mran.microsoft.com/snapshot/2018-07-01

script:
    - |
        Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook")'
        Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::pdf_book")'

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
    keep-history: true
    local-dir: docs
    verbose: true
